// <auto-generated />
using System;
using Kolos_2_s_30781_GR_E.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos_2_s_30781_GR_E.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250613103936_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NurseryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SownDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NurseryId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Anna",
                            LastName = "Kowalska"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        });
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.EmployeeBatch", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("EmployeeBatches");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Nursery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nurseries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstablishedDate = new DateTime(2005, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Green Forest Nursery"
                        });
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrowthTimeInYears")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GrowthTimeInYears = 5,
                            LatinName = "Quercus robur"
                        });
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Batch", b =>
                {
                    b.HasOne("Kolos_2_s_30781_GR_E.Models.Nursery", "Nursery")
                        .WithMany("Batches")
                        .HasForeignKey("NurseryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos_2_s_30781_GR_E.Models.Species", "Species")
                        .WithMany("Batches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nursery");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.EmployeeBatch", b =>
                {
                    b.HasOne("Kolos_2_s_30781_GR_E.Models.Batch", "Batch")
                        .WithMany("EmployeeBatches")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos_2_s_30781_GR_E.Models.Employee", "Employee")
                        .WithMany("EmployeeBatches")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Batch", b =>
                {
                    b.Navigation("EmployeeBatches");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Employee", b =>
                {
                    b.Navigation("EmployeeBatches");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Nursery", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Kolos_2_s_30781_GR_E.Models.Species", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
